### ISSUE TITLE
Some npcs that are spawned into the game cannot die.

### ISSUE THREAD

**Issue by tikki100** [stoneharry/LightsDawnBugTracker#19]
NPC's like Lesser Ghoul that are spawned at the Northshire Entrance does not die.

This is also the case in Stormwind, where npcs such as Blistering Zombie, Dark Necromancer and Zombie Chow will not die, not even with the .die command.

This hinders any progress that might be made, and is dangerous at the entrance, as the NPC's can still attack and kill players.

So far, a lot of information surrounding the bug is cloacked in mystery.

I've only experienced it happening with NPC's spawned with the SpawnCreature() Lua command.

**Comment by stoneharry** [comment]
I think it's related to Terrorblade's changes, we need to rollback and see if it still happens.

**Comment by Terrorblade** [comment]
Should be fixed in 04061adc0a9320a90b0126af0a15b28195dc55c3.

**Comment by stoneharry** [comment]
Need to test. Will deploy a new build to the server now, will see if it is still happening after a few days.
