### ISSUE TITLE
Cosmetic Object shows it's name

### ISSUE THREAD

**Issue by tikki100** [stoneharry/LightsDawnBugTracker#27]
Change it so that object "Rune Cosmetic 1" entry: 90009 is no longer selectable.

**Comment by stoneharry** [comment]
Did you forget that if you have GM on you can see invisible units? ;)

**Comment by tikki100** [comment]
Tooltip was showing even with GM off - There was a table, (data0 I think ), that decided whether the tooltip should be pushed to the player or not :)
